# Primary accent color for interactive elements.
primaryColor = "#FBF9F1"

# Background color for the main content area.
backgroundColor = "#AAD7D9"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#FBF9F1"

# Color used for almost all text.
textColor = "#FFFFEC"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif" 
